# Generated by Django 4.2.1 on 2023-11-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionProyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('importante', models.BooleanField(default=True)),
            ],
        ),
    ]
