# Generated by Django 4.2.1 on 2023-11-03 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracionProyecto', '0002_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracionProyecto.proyecto'),
        ),
    ]
