# Generated by Django 4.2.1 on 2023-11-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionProyecto', '0003_reporte_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='importante',
            field=models.BooleanField(default=False),
        ),
    ]
