# Generated by Django 4.2.1 on 2023-11-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionProyecto', '0004_alter_reporte_importante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='importante',
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
