# Generated by Django 4.2.1 on 2023-11-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_profile_dui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
