# Generated by Django 4.2.6 on 2023-10-29 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='Pendiente', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=50)),
                ('objetivo', models.CharField(max_length=255)),
                ('prioridad', models.CharField(max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadoProyecto', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionarProyecto.estado'), max_length=15)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionarProyecto.estado')),
            ],
        ),
    ]
