# Generated by Django 4.2.6 on 2023-10-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarProyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='estado',
        ),
        migrations.AddField(
            model_name='estado',
            name='enProceso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estado',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estado',
            name='pendiente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estadoProyecto',
            field=models.CharField(default='Pendiente', max_length=15),
        ),
    ]
