# Generated by Django 4.2.6 on 2023-10-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarProyecto', '0002_remove_estado_estado_estado_enproceso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='estadoProyecto',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=15),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
