# Generated by Django 4.2.6 on 2023-10-29 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrarProyecto', '0002_remove_tarea_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionarProyecto', '0003_remove_proyecto_estadoproyecto_alter_proyecto_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tarea',
            field=models.ManyToManyField(blank=True, to='administrarProyecto.tarea'),
        ),
    ]
