# Generated by Django 4.2.6 on 2023-10-31 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionarProyecto', '0004_proyecto_encargado_proyecto_tarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='tarea',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='encargadoProyecto',
            field=models.CharField(default='no asignado', max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
