# Generated by Django 4.2.6 on 2023-10-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrarProyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='proyecto',
        ),
    ]
