# Generated by Django 4.2.6 on 2023-10-31 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarProyecto', '0005_remove_proyecto_tarea_proyecto_encargadoproyecto_and_more'),
        ('administrarProyecto', '0002_remove_tarea_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='encargado',
            field=models.CharField(default='no asignado', max_length=50),
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionarProyecto.proyecto'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
