# Generated by Django 4.2.6 on 2023-10-31 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarProyecto', '0005_remove_proyecto_tarea_proyecto_encargadoproyecto_and_more'),
        ('administrarProyecto', '0003_tarea_encargado_tarea_proyecto_alter_tarea_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionarProyecto.proyecto')),
            ],
        ),
    ]
