# Generated by Django 4.2.6 on 2023-10-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrarProyecto', '0004_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
